import os
import re
from datetime import datetime
from pathlib import Path

from docx import Document
from docx.enum.section import WD_SECTION
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt, RGBColor


DOCUMENT_DIR = Path(
    "data/documents"
)


THEMES = {
    "professional": {
        "accent": RGBColor(31, 78, 121),
        "accent_hex": "1F4E79",
        "dark": RGBColor(25, 35, 50),
        "muted": RGBColor(90, 105, 125),
        "light_hex": "EAF2F8"
    },
    "school": {
        "accent": RGBColor(40, 90, 180),
        "accent_hex": "285AB4",
        "dark": RGBColor(30, 45, 75),
        "muted": RGBColor(85, 100, 130),
        "light_hex": "EDF3FF"
    },
    "essay": {
        "accent": RGBColor(70, 70, 70),
        "accent_hex": "464646",
        "dark": RGBColor(25, 25, 25),
        "muted": RGBColor(90, 90, 90),
        "light_hex": "F2F2F2"
    },
    "notes": {
        "accent": RGBColor(0, 135, 105),
        "accent_hex": "008769",
        "dark": RGBColor(20, 55, 50),
        "muted": RGBColor(80, 110, 105),
        "light_hex": "E8F7F2"
    }
}


class DocumentMaker:

    def ensure_output_folder(
        self
    ):
        DOCUMENT_DIR.mkdir(
            parents=True,
            exist_ok=True
        )

    def sanitize_filename(
        self,
        text: str
    ) -> str:
        text = str(text).lower().strip()

        text = re.sub(
            r"[^a-z0-9]+",
            "_",
            text
        )

        text = text.strip("_")

        if not text:
            text = "document"

        return text[:60]

    def clean_topic(
        self,
        topic: str
    ) -> str:
        topic = str(topic).strip()

        if not topic:
            return "Untitled Document"

        return topic[0].upper() + topic[1:]

    def create_output_path(
        self,
        topic: str,
        doc_type: str
    ) -> Path:
        self.ensure_output_folder()

        timestamp = datetime.now().strftime(
            "%Y-%m-%d_%H-%M-%S"
        )

        filename = (
            f"{self.sanitize_filename(topic)}_"
            f"{self.sanitize_filename(doc_type)}_"
            f"{timestamp}.docx"
        )

        return DOCUMENT_DIR / filename

    def set_cell_background(
        self,
        cell,
        fill_hex: str
    ):
        tc_pr = cell._tc.get_or_add_tcPr()

        shading = OxmlElement(
            "w:shd"
        )

        shading.set(
            qn("w:fill"),
            fill_hex
        )

        tc_pr.append(
            shading
        )

    def set_cell_text(
        self,
        cell,
        text: str,
        bold: bool = False,
        color=None
    ):
        cell.text = ""

        paragraph = cell.paragraphs[0]
        run = paragraph.add_run(
            text
        )

        run.font.name = "Aptos"
        run.font.size = Pt(
            10.5
        )
        run.font.bold = bold

        if color is not None:
            run.font.color.rgb = color

    def configure_document(
        self,
        document,
        theme: dict,
        topic: str,
        doc_type: str
    ):
        section = document.sections[0]
        section.top_margin = Inches(
            0.75
        )
        section.bottom_margin = Inches(
            0.75
        )
        section.left_margin = Inches(
            0.8
        )
        section.right_margin = Inches(
            0.8
        )

        normal_style = document.styles["Normal"]
        normal_style.font.name = "Aptos"
        normal_style.font.size = Pt(
            11
        )
        normal_style.font.color.rgb = theme["dark"]

        footer = section.footer
        paragraph = footer.paragraphs[0]
        paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER

        run = paragraph.add_run(
            f"Generated by Jarvis • {doc_type.title()} • {topic}"
        )
        run.font.name = "Aptos"
        run.font.size = Pt(
            8
        )
        run.font.color.rgb = theme["muted"]

    def add_title_page(
        self,
        document,
        topic: str,
        doc_type: str,
        theme: dict
    ):
        paragraph = document.add_paragraph()
        paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER

        run = paragraph.add_run(
            "JARVIS DOCUMENT"
        )
        run.font.name = "Aptos"
        run.font.size = Pt(
            12
        )
        run.font.bold = True
        run.font.color.rgb = theme["accent"]

        document.add_paragraph()

        title = document.add_paragraph()
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER

        title_run = title.add_run(
            topic
        )
        title_run.font.name = "Aptos Display"
        title_run.font.size = Pt(
            30
        )
        title_run.font.bold = True
        title_run.font.color.rgb = theme["dark"]

        subtitle = document.add_paragraph()
        subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER

        subtitle_run = subtitle.add_run(
            doc_type.title()
        )
        subtitle_run.font.name = "Aptos"
        subtitle_run.font.size = Pt(
            16
        )
        subtitle_run.font.color.rgb = theme["muted"]

        document.add_paragraph()

        date_text = datetime.now().strftime(
            "%d %B %Y"
        )

        date_para = document.add_paragraph()
        date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

        date_run = date_para.add_run(
            date_text
        )
        date_run.font.name = "Aptos"
        date_run.font.size = Pt(
            11
        )
        date_run.font.color.rgb = theme["muted"]

        document.add_page_break()

    def add_section_heading(
        self,
        document,
        text: str,
        theme: dict
    ):
        paragraph = document.add_paragraph()
        paragraph.space_before = Pt(
            10
        )
        paragraph.space_after = Pt(
            5
        )

        run = paragraph.add_run(
            text
        )
        run.font.name = "Aptos Display"
        run.font.size = Pt(
            17
        )
        run.font.bold = True
        run.font.color.rgb = theme["accent"]

    def add_body_paragraph(
        self,
        document,
        text: str
    ):
        paragraph = document.add_paragraph()
        paragraph.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
        paragraph.space_after = Pt(
            7
        )

        run = paragraph.add_run(
            text
        )
        run.font.name = "Aptos"
        run.font.size = Pt(
            11
        )

    def add_bullets(
        self,
        document,
        bullets: list[str]
    ):
        for bullet in bullets:
            paragraph = document.add_paragraph(
                style="List Bullet"
            )
            paragraph.space_after = Pt(
                4
            )

            run = paragraph.add_run(
                bullet
            )
            run.font.name = "Aptos"
            run.font.size = Pt(
                11
            )

    def add_key_points_table(
        self,
        document,
        rows: list[tuple[str, str]],
        theme: dict
    ):
        table = document.add_table(
            rows=1,
            cols=2
        )

        table.alignment = WD_TABLE_ALIGNMENT.CENTER
        table.style = "Table Grid"

        header_cells = table.rows[0].cells

        self.set_cell_background(
            header_cells[0],
            theme["accent_hex"]
        )

        self.set_cell_background(
            header_cells[1],
            theme["accent_hex"]
        )

        self.set_cell_text(
            header_cells[0],
            "Key Area",
            bold=True,
            color=RGBColor(255, 255, 255)
        )

        self.set_cell_text(
            header_cells[1],
            "Explanation",
            bold=True,
            color=RGBColor(255, 255, 255)
        )

        for key_area, explanation in rows:
            cells = table.add_row().cells

            self.set_cell_background(
                cells[0],
                theme["light_hex"]
            )

            self.set_cell_text(
                cells[0],
                key_area,
                bold=True
            )

            self.set_cell_text(
                cells[1],
                explanation
            )

        document.add_paragraph()

    def build_content(
        self,
        topic: str,
        doc_type: str
    ) -> dict:
        topic = self.clean_topic(
            topic
        )

        if doc_type == "notes":
            return {
                "intro_title": "Overview",
                "intro": [
                    f"These notes provide a clear and organized overview of {topic}.",
                    "The aim is to make the topic easier to revise, understand, and explain."
                ],
                "table": [
                    (
                        "Definition",
                        f"A clear understanding of {topic} starts with its basic meaning and purpose."
                    ),
                    (
                        "Importance",
                        "The topic is important because it connects ideas, examples, and real-world use."
                    ),
                    (
                        "Application",
                        "It can be applied through examples, case studies, practice questions, and comparisons."
                    )
                ],
                "sections": [
                    (
                        "Important Points",
                        [],
                        [
                            f"Understand the main idea behind {topic}.",
                            "Learn the key terms and definitions.",
                            "Connect each point with examples.",
                            "Revise using short explanations and question-answer practice."
                        ]
                    ),
                    (
                        "Quick Revision",
                        [
                            "A good revision method is to divide the topic into smaller parts and review each part separately."
                        ],
                        [
                            "What is the topic about?",
                            "Why is it important?",
                            "Where is it used?",
                            "What are the advantages and limitations?"
                        ]
                    )
                ],
                "conclusion": [
                    f"{topic} can be revised effectively by focusing on meaning, examples, and key takeaways."
                ]
            }

        if doc_type == "essay":
            return {
                "intro_title": "Introduction",
                "intro": [
                    f"{topic} is a topic that can be examined through its causes, effects, and wider importance.",
                    "A balanced essay should explain the main idea, develop arguments, and end with a clear conclusion."
                ],
                "table": [
                    (
                        "Main Argument",
                        f"The central argument should clearly explain why {topic} matters."
                    ),
                    (
                        "Evidence",
                        "Examples, facts, comparisons, or case studies should support each point."
                    ),
                    (
                        "Evaluation",
                        "A strong essay considers both strengths and limitations."
                    )
                ],
                "sections": [
                    (
                        "Main Discussion",
                        [
                            f"The discussion of {topic} should begin with the most important background information.",
                            "This helps the reader understand the context before moving into deeper analysis."
                        ],
                        [
                            "Explain the first major point clearly.",
                            "Support it with an example or explanation.",
                            "Link the point back to the main question."
                        ]
                    ),
                    (
                        "Further Analysis",
                        [
                            "A strong essay also considers different perspectives and possible limitations.",
                            "This makes the response more balanced and mature."
                        ],
                        [
                            "Compare different viewpoints.",
                            "Explain possible challenges.",
                            "Show why one argument may be stronger than another."
                        ]
                    )
                ],
                "conclusion": [
                    f"In conclusion, {topic} should be understood through clear explanation, evidence, and balanced judgement.",
                    "The strongest essays are structured, relevant, and supported by examples."
                ]
            }

        if doc_type == "school":
            return {
                "intro_title": "Introduction",
                "intro": [
                    f"This assignment explains {topic} in a simple and structured way.",
                    "It includes the meaning, importance, key points, examples, and conclusion."
                ],
                "table": [
                    (
                        "Meaning",
                        f"{topic} refers to an important idea that can be understood through explanation and examples."
                    ),
                    (
                        "Importance",
                        "It is useful because it helps us understand real-life situations and solve problems."
                    ),
                    (
                        "Examples",
                        "Examples make the concept easier to understand and remember."
                    )
                ],
                "sections": [
                    (
                        "Explanation",
                        [
                            f"{topic} can be explained by breaking it into smaller and simpler ideas.",
                            "Each idea should be connected with examples so the topic becomes clearer."
                        ],
                        [
                            "Start with the basic meaning.",
                            "Explain the important features.",
                            "Use examples wherever possible.",
                            "End with a short summary."
                        ]
                    ),
                    (
                        "Advantages and Challenges",
                        [
                            "Most topics have both benefits and challenges. Explaining both makes the assignment more complete."
                        ],
                        [
                            "Advantages show why the topic is useful.",
                            "Challenges show what problems or limitations may exist.",
                            "Solutions explain how these challenges can be reduced."
                        ]
                    )
                ],
                "conclusion": [
                    f"Overall, {topic} is important because it helps us understand the subject in a practical way.",
                    "A clear structure makes the assignment easier to read and present."
                ]
            }

        return {
            "intro_title": "Executive Summary",
            "intro": [
                f"This document presents a professional overview of {topic}.",
                "It is designed to explain the topic clearly, identify key areas, and provide a structured direction for further work."
            ],
            "table": [
                (
                    "Purpose",
                    f"Clarifies why {topic} matters and what objective it supports."
                ),
                (
                    "Impact",
                    "Explains the possible benefits, limitations, and outcomes."
                ),
                (
                    "Action",
                    "Identifies practical steps, recommendations, and next actions."
                )
            ],
            "sections": [
                (
                    "Background and Context",
                    [
                        f"{topic} should be understood through its background, current relevance, and practical value.",
                        "A clear context helps connect the subject to real decisions, planning, and communication."
                    ],
                    [
                        "Define the core purpose.",
                        "Identify the major stakeholders or users.",
                        "Understand the current situation.",
                        "Connect the topic to practical outcomes."
                    ]
                ),
                (
                    "Analysis",
                    [
                        "A professional analysis focuses on the most important factors instead of unnecessary details.",
                        "The topic should be evaluated using clear categories such as benefits, risks, opportunities, and limitations."
                    ],
                    [
                        "Break the topic into key components.",
                        "Compare advantages and disadvantages.",
                        "Use relevant examples or case studies.",
                        "Focus on useful conclusions."
                    ]
                ),
                (
                    "Recommendations",
                    [
                        "Recommendations should be practical, clear, and connected to the main objective."
                    ],
                    [
                        "Improve clarity by using structured planning.",
                        "Support ideas with data or examples.",
                        "Review possible risks before final decisions.",
                        "Update the document with topic-specific research later."
                    ]
                )
            ],
            "conclusion": [
                f"{topic} can be presented effectively when the information is structured, relevant, and easy to follow.",
                "The next improvement should be to add specific research, charts, images, or case studies."
            ]
        }

    def create_document(
        self,
        topic: str,
        doc_type: str = "professional"
    ) -> str:
        topic = self.clean_topic(
            topic
        )

        doc_type = str(
            doc_type
        ).lower().strip()

        if doc_type not in THEMES:
            doc_type = "professional"

        theme = THEMES[doc_type]

        content = self.build_content(
            topic,
            doc_type
        )

        document = Document()

        self.configure_document(
            document,
            theme,
            topic,
            doc_type
        )

        self.add_title_page(
            document,
            topic,
            doc_type,
            theme
        )

        self.add_section_heading(
            document,
            content["intro_title"],
            theme
        )

        for paragraph in content["intro"]:
            self.add_body_paragraph(
                document,
                paragraph
            )

        self.add_section_heading(
            document,
            "Key Points",
            theme
        )

        self.add_key_points_table(
            document,
            content["table"],
            theme
        )

        for title, paragraphs, bullets in content["sections"]:
            self.add_section_heading(
                document,
                title,
                theme
            )

            for paragraph in paragraphs:
                self.add_body_paragraph(
                    document,
                    paragraph
                )

            if bullets:
                self.add_bullets(
                    document,
                    bullets
                )

        self.add_section_heading(
            document,
            "Conclusion",
            theme
        )

        for paragraph in content["conclusion"]:
            self.add_body_paragraph(
                document,
                paragraph
            )

        output_path = self.create_output_path(
            topic,
            doc_type
        )

        document.save(
            output_path
        )

        return f"Document created: {output_path}"

    def open_document_folder(
        self
    ) -> str:
        try:
            self.ensure_output_folder()

            os.startfile(
                str(DOCUMENT_DIR.resolve())
            )

            return "Opening documents folder."

        except Exception as e:
            return f"Failed to open documents folder: {e}"