import json
import subprocess
from pathlib import Path


DATA_FILE = Path("data/uwp_apps.json")


BAD_APP_NAME_WORDS = [
    "documentation",
    "help",
    "faq",
    "release notes",
    "website",
    "command prompt",
    "install additional tools",
]


BAD_APP_ID_PARTS = [
    "\\",
    ".exe",
    ".chm",
    ".url",
    "http://",
    "https://",
    "steam://",
    "microsoft.autogenerated",
]


class UWPDiscovery:

    def __init__(self):
        self.apps = {}

    def normalize_name(self, name: str) -> str:
        return str(name).lower().strip()

    def is_bad_name(self, name: str) -> bool:
        name = self.normalize_name(name)

        return any(
            word in name
            for word in BAD_APP_NAME_WORDS
        )

    def is_valid_uwp_app_id(self, app_id: str) -> bool:
        app_id = str(app_id).strip()
        lowered = app_id.lower()

        if not app_id:
            return False

        if "!" not in app_id:
            return False

        return not any(
            bad_part in lowered
            for bad_part in BAD_APP_ID_PARTS
        )

    def save(self):
        DATA_FILE.parent.mkdir(
            parents=True,
            exist_ok=True
        )

        with open(
            DATA_FILE,
            "w",
            encoding="utf-8"
        ) as f:
            json.dump(
                self.apps,
                f,
                indent=4
            )

    def load(self):
        if not DATA_FILE.exists():
            return {}

        with open(
            DATA_FILE,
            "r",
            encoding="utf-8"
        ) as f:
            self.apps = json.load(f)

        return self.apps

    def scan_all(self):
        command = [
            "powershell",
            "-NoProfile",
            "-Command",
            "Get-StartApps | Select-Object Name,AppID | ConvertTo-Json"
        ]

        try:
            result = subprocess.run(
                command,
                capture_output=True,
                text=True,
                timeout=20
            )

            if result.returncode != 0:
                return {}

            output = result.stdout.strip()

            if not output:
                return {}

            raw_apps = json.loads(output)

            if isinstance(raw_apps, dict):
                raw_apps = [raw_apps]

            apps = {}

            for item in raw_apps:
                name = item.get("Name")
                app_id = item.get("AppID")

                if not name or not app_id:
                    continue

                app_name = self.normalize_name(name)

                if self.is_bad_name(app_name):
                    continue

                if not self.is_valid_uwp_app_id(app_id):
                    continue

                apps[app_name] = app_id

            self.apps = dict(
                sorted(
                    apps.items()
                )
            )

            self.save()

            return self.apps

        except Exception:
            return {}

    def scan_with_summary(self):
        old_apps = self.load()
        new_apps = self.scan_all()

        added = {}
        removed = {}
        updated = {}

        for app_name, app_id in new_apps.items():
            if app_name not in old_apps:
                added[app_name] = app_id
                continue

            if old_apps[app_name] != app_id:
                updated[app_name] = {
                    "old": old_apps[app_name],
                    "new": app_id
                }

        for app_name, app_id in old_apps.items():
            if app_name not in new_apps:
                removed[app_name] = app_id

        return {
            "total": len(new_apps),
            "added": added,
            "removed": removed,
            "updated": updated,
            "apps": new_apps
        }